# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://kylozw.github.io
date_format: "ordinal"
title: kylo
subtitle: "change the world"
description: "kylo's blog'"
keywords: kylo, kylozw
favicon: /favicon.ico
timezone: Asia/Hangzhou
encoding: "utf-8"
source_code: https://github.com/kylozw/kylozw.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: Wang Zhang
organization: Songxiaocai, Inc.
organization_url: https://www.songxiaocai.com
location: Hangzhou, China
email: kylo.zw@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: kylozw
douban_username: 黑の透明
facebook_username: kylo
weibo_username: kylozw
# zhihu_username: kylozw
# twitter_username: kylozw

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# duoshuo_username: kylo
disqus_username: kylo

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Python, Design Patterns]
skill_mobile_app_keywords:
skill_windows_keywords:
popular_repos:
contribute_repos:
